FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY Backend/Backend.csproj ./Backend/
WORKDIR /app/Backend
RUN dotnet restore

COPY Backend/. ./
RUN dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/out ./

EXPOSE 8080

ENTRYPOINT ["dotnet", "Backend.dll"]
